Repository louvill/AAE535dPCalc, pull requests merged in 2020-04, with the labels that each got.

#25 Finalize Data Structure and create A21.py
  SysEng/dataInputFormat.md
  bin/A21.py
  bin/recusionExample.py
Labels: Core, Non-Programming, Python

#28 Set up alpha version [CR]
  SysEng/dataInputFormat.md
  alphaTest.py
  bin/A11.py
  bin/A21.py
  bin/A22.py
  bin/A31.py
  bin/__init__.py
  bin/__pycache__/A11.cpython-38.pyc
  bin/__pycache__/A21.cpython-38.pyc
  bin/__pycache__/A21func.cpython-38.pyc
  bin/__pycache__/A21sub.cpython-38.pyc
  bin/__pycache__/A22.cpython-38.pyc
  bin/__pycache__/A31.cpython-38.pyc
  bin/__pycache__/A32.cpython-38.pyc
  bin/__pycache__/__init__.cpython-38.pyc
  bin/__pycache__/suddenContractionKtRegression.cpython-38.pyc
  bin/suddenContractionKtRegression.py
Labels: Python, enhancement

#37 Create units.json
  lib/units.json
Labels: Core, Electron
